name: gertty
version: '1.5.0'
summary: Console interface to Gerrit Code Review
description: |
  Gertty is a console-based interface to the Gerrit Code Review system.

  As compared to the web interface, the main advantages are:

  * Workflow -- the interface is designed to support a workflow similar
  to reading network news or mail. In particular, it is designed to
  deal with a large number of review requests across a large number of
  projects.

  * Offline Use -- Gertty syncs information about changes in
  subscribed projects to a local database and local git repos.
  All review operations are performed against that database and
  then synced back to Gerrit.

  * Speed -- user actions modify locally cached content
  and need not wait for server interaction.

  * Convenience -- because Gertty downloads all
  changes to local git repos, a single command
  instructs it to checkout a change into that
  repo for detailed examination or testing of
  larger changes.

grade: stable
confinement: strict

parts:
  gertty:
    plugin: python
    python-version: python3
    source: .
    source-tag: 1.5.0
    python-packages:
      - pbr>=0.11
      - urwid>=1.2.1,!=1.3.0
      - SQLAlchemy>=1.0.4
      - GitPython>=0.3.7
      - python-dateutil
      - requests>=2.5.3,<3.0.0
      - ordereddict
      - alembic>=0.6.4
      - PyYAML>=3.1.0
      - voluptuous>=0.7
      - ply>=3.4
      - six
    stage-packages:
      - git
      - libdb5.3

apps:
  gertty:
    command: bin/gertty
